#include "nsISupports.idl"

interface nsIDOMElement;

[scriptable, uuid(14027e96-1afb-4066-8846-e6c89b5faf3b)]
interface nsICSRPolicy : nsISupports
{
  void registerFormSubmitted(in ACString originUrl, in ACString destinationUrl);
  
  void registerLinkClicked(in ACString originUrl, in ACString destinationUrl);
  
  void temporarilyAllowOriginHost(in ACString host);
  
  void revokeTemporarilyAllowedOriginHost(in ACString host);
  
  boolean isTemporarilyAllowedOriginHost(in ACString host);
};  
