#include "nsISupports.idl"

interface nsIDOMElement;
interface nsIPrefBranch;

[scriptable, uuid(14027e96-1afb-4066-8846-e6c89b5faf3b)]
interface nsICSRPolicy : nsISupports
{
  void registerFormSubmitted(in ACString originUrl, in ACString destinationUrl);
  void registerLinkClicked(in ACString originUrl, in ACString destinationUrl);
  
  void temporarilyAllowOrigin(in ACString host);
  boolean isTemporarilyAllowedOrigin(in ACString host);
  
  void allowOrigin(in ACString host);
  boolean isAllowedOrigin(in ACString host);
  
  void temporarilyAllowDestination(in ACString host);
  boolean isTemporarilyAllowedDestination(in ACString host);
  
  void allowDestination(in ACString host);
  boolean isAllowedDestination(in ACString host);
  
  void revokeTemporaryPermissions();
  
  void forbidOrigin(in ACString host);
  void forbidDestination(in ACString host);
  
  readonly attribute nsIPrefBranch prefs;
};  
