#include "nsISupports.idl"

interface nsIDOMElement;
interface nsIPrefBranch;

[scriptable, uuid(14027e96-1afb-4066-8846-e6c89b5faf3b)]
interface nsIRequestPolicy : nsISupports
{
  ACString getUriIdentifier(in ACString uri);

  void registerFormSubmitted(in ACString originUri, in ACString destinationUri);
  void registerLinkClicked(in ACString originUri, in ACString destinationUri);
  
  void temporarilyAllowOrigin(in ACString siteIdentifier);
  boolean isTemporarilyAllowedOrigin(in ACString siteIdentifier);
  
  void allowOrigin(in ACString siteIdentifier);
  boolean isAllowedOrigin(in ACString siteIdentifier);
  
  void temporarilyAllowDestination(in ACString siteIdentifier);
  boolean isTemporarilyAllowedDestination(in ACString siteIdentifier);
  
  void allowDestination(in ACString siteIdentifier);
  boolean isAllowedDestination(in ACString siteIdentifier);
  
  void temporarilyAllowOriginToDestination(in ACString originIdentifier, in ACString destinationIdentifier);
  boolean isTemporarilyAllowedOriginToDestination(in ACString originIdentifier, in ACString destinationIdentifier);
  
  void allowOriginToDestination(in ACString originIdentifier, in ACString destinationIdentifier);
  boolean isAllowedOriginToDestination(in ACString originIdentifier, in ACString destinationIdentifier);
  
  void revokeTemporaryPermissions();
  boolean areTemporaryPermissionsGranted();
  
  void forbidOrigin(in ACString siteIdentifier);
  void forbidDestination(in ACString siteIdentifier);
  void forbidOriginToDestination(in ACString originIdentifier, in ACString destinationIdentifier);
  
  boolean isAllowedRedirect(in ACString originUri, in ACString destinationUri);
  
  boolean isPrefetchEnabled();
  
  boolean originHasRejectedRequests(in ACString originUri);
  boolean originHasRejectedRequestsRecursive(in ACString originUri);
  
  readonly attribute nsIPrefBranch prefs;
};  
